%General Mission Analysis Tool(GMAT) Script
%Created: 2026-08-06 11:34:53


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft LEOsat;
GMAT LEOsat.DateFormat = UTCGregorian;
GMAT LEOsat.Epoch = '01 Jan 2000 11:59:28.000';
GMAT LEOsat.CoordinateSystem = EarthMJ2000Eq;
GMAT LEOsat.DisplayStateType = Keplerian;
GMAT LEOsat.SMA = 6778.140000000001;
GMAT LEOsat.ECC = 2.416534272185428e-16;
GMAT LEOsat.INC = 51.60000000000001;
GMAT LEOsat.RAAN = 0;
GMAT LEOsat.AOP = 0;
GMAT LEOsat.TA = 0;
GMAT LEOsat.DryMass = 100;
GMAT LEOsat.Cd = 2.2;
GMAT LEOsat.Cr = 1.8;
GMAT LEOsat.DragArea = 15;
GMAT LEOsat.SRPArea = 1;
GMAT LEOsat.SPADDragScaleFactor = 1;
GMAT LEOsat.SPADSRPScaleFactor = 1;
GMAT LEOsat.AtmosDensityScaleFactor = 1;
GMAT LEOsat.ExtendedMassPropertiesModel = 'None';
GMAT LEOsat.NAIFId = -10000001;
GMAT LEOsat.NAIFIdReferenceFrame = -9000001;
GMAT LEOsat.OrbitColor = Red;
GMAT LEOsat.TargetColor = Teal;
GMAT LEOsat.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT LEOsat.CdSigma = 1e+70;
GMAT LEOsat.CrSigma = 1e+70;
GMAT LEOsat.Id = 'SatId';
GMAT LEOsat.Attitude = CoordinateSystemFixed;
GMAT LEOsat.SPADSRPInterpolationMethod = Bilinear;
GMAT LEOsat.SPADSRPScaleFactorSigma = 1e+70;
GMAT LEOsat.SPADDragInterpolationMethod = Bilinear;
GMAT LEOsat.SPADDragScaleFactorSigma = 1e+70;
GMAT LEOsat.AtmosDensityScaleFactorSigma = 1e+70;
GMAT LEOsat.ModelFile = 'aura.3ds';
GMAT LEOsat.ModelOffsetX = 0;
GMAT LEOsat.ModelOffsetY = 0;
GMAT LEOsat.ModelOffsetZ = 0;
GMAT LEOsat.ModelRotationX = 0;
GMAT LEOsat.ModelRotationY = 0;
GMAT LEOsat.ModelRotationZ = 0;
GMAT LEOsat.ModelScale = 1;
GMAT LEOsat.AttitudeDisplayStateType = 'Quaternion';
GMAT LEOsat.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT LEOsat.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT LEOsat.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';
GMAT DefaultProp_ForceModel.Drag.AtmosphereModel = JacchiaRoberts;
GMAT DefaultProp_ForceModel.Drag.HistoricWeatherSource = 'ConstantFluxAndGeoMag';
GMAT DefaultProp_ForceModel.Drag.PredictedWeatherSource = 'ConstantFluxAndGeoMag';
GMAT DefaultProp_ForceModel.Drag.CSSISpaceWeatherFile = 'SpaceWeather-All-v1.2.txt';
GMAT DefaultProp_ForceModel.Drag.SchattenFile = 'SchattenPredict.txt';
GMAT DefaultProp_ForceModel.Drag.F107 = 150;
GMAT DefaultProp_ForceModel.Drag.F107A = 150;
GMAT DefaultProp_ForceModel.Drag.MagneticIndex = 3;
GMAT DefaultProp_ForceModel.Drag.SchattenErrorModel = 'Nominal';
GMAT DefaultProp_ForceModel.Drag.SchattenTimingModel = 'NominalCycle';
GMAT DefaultProp_ForceModel.Drag.DragModel = 'Spherical';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn Burn1_Drag;
GMAT Burn1_Drag.CoordinateSystem = Local;
GMAT Burn1_Drag.Origin = Earth;
GMAT Burn1_Drag.Axes = VNB;
GMAT Burn1_Drag.Element1 = 0.00566;
GMAT Burn1_Drag.Element2 = 0;
GMAT Burn1_Drag.Element3 = 0;
GMAT Burn1_Drag.DecrementMass = false;
GMAT Burn1_Drag.Isp = 300;
GMAT Burn1_Drag.GravitationalAccel = 9.81;

Create ImpulsiveBurn Burn2_Drag;
GMAT Burn2_Drag.CoordinateSystem = Local;
GMAT Burn2_Drag.Origin = Earth;
GMAT Burn2_Drag.Axes = VNB;
GMAT Burn2_Drag.Element1 = 0.00566;
GMAT Burn2_Drag.Element2 = 0;
GMAT Burn2_Drag.Element3 = 0;
GMAT Burn2_Drag.DecrementMass = false;
GMAT Burn2_Drag.Isp = 300;
GMAT Burn2_Drag.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.002173913043478261 0 ];
GMAT DefaultOrbitView.Size = [ 0.4992753623188406 0.4484848484848485 ];
GMAT DefaultOrbitView.RelativeZOrder = 155;
GMAT DefaultOrbitView.Maximized = true;
GMAT DefaultOrbitView.Add = {LEOsat, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.002898550724637681 0.4545454545454545 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.5 0.45 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 151;
GMAT DefaultGroundTrackPlot.Maximized = true;
GMAT DefaultGroundTrackPlot.Add = {LEOsat};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create XYPlot XYPlot1;
GMAT XYPlot1.SolverIterations = Current;
GMAT XYPlot1.UpperLeft = [ 0.3202898550724638 0.1878787878787879 ];
GMAT XYPlot1.Size = [ 0.5 0.45 ];
GMAT XYPlot1.RelativeZOrder = 159;
GMAT XYPlot1.Maximized = true;
GMAT XYPlot1.XVariable = LEOsat.ElapsedDays;
GMAT XYPlot1.YVariables = {LEOsat.Earth.SMA};
GMAT XYPlot1.ShowGrid = true;
GMAT XYPlot1.ShowPlot = true;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(LEOsat) {LEOsat.ElapsedDays = 5, OrbitColor = [0 128 255]};
Maneuver Burn1_Drag(LEOsat);
Propagate DefaultProp(LEOsat) {LEOsat.Earth.Apoapsis, OrbitColor = [255 255 128]};
Maneuver Burn2_Drag(LEOsat);
Propagate DefaultProp(LEOsat) {LEOsat.ElapsedDays = 5, OrbitColor = [255 0 0]};
