%General Mission Analysis Tool(GMAT) Script
%Created: 2026-08-04 16:29:55


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Chaser;
GMAT Chaser.DateFormat = UTCGregorian;
GMAT Chaser.Epoch = '01 Jan 2000 11:59:28.000';
GMAT Chaser.CoordinateSystem = EarthMJ2000Eq;
GMAT Chaser.DisplayStateType = Keplerian;
GMAT Chaser.SMA = 6878;
GMAT Chaser.ECC = 0;
GMAT Chaser.INC = 28.5;
GMAT Chaser.RAAN = 0;
GMAT Chaser.AOP = 0;
GMAT Chaser.TA = 0;
GMAT Chaser.DryMass = 850;
GMAT Chaser.Cd = 2.2;
GMAT Chaser.Cr = 1.8;
GMAT Chaser.DragArea = 15;
GMAT Chaser.SRPArea = 1;
GMAT Chaser.SPADDragScaleFactor = 1;
GMAT Chaser.SPADSRPScaleFactor = 1;
GMAT Chaser.AtmosDensityScaleFactor = 1;
GMAT Chaser.ExtendedMassPropertiesModel = 'None';
GMAT Chaser.NAIFId = -10000001;
GMAT Chaser.NAIFIdReferenceFrame = -9000001;
GMAT Chaser.OrbitColor = Red;
GMAT Chaser.TargetColor = Teal;
GMAT Chaser.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT Chaser.CdSigma = 1e+70;
GMAT Chaser.CrSigma = 1e+70;
GMAT Chaser.Id = 'SatId';
GMAT Chaser.Attitude = CoordinateSystemFixed;
GMAT Chaser.SPADSRPInterpolationMethod = Bilinear;
GMAT Chaser.SPADSRPScaleFactorSigma = 1e+70;
GMAT Chaser.SPADDragInterpolationMethod = Bilinear;
GMAT Chaser.SPADDragScaleFactorSigma = 1e+70;
GMAT Chaser.AtmosDensityScaleFactorSigma = 1e+70;
GMAT Chaser.ModelFile = 'aura.3ds';
GMAT Chaser.ModelOffsetX = 0;
GMAT Chaser.ModelOffsetY = 0;
GMAT Chaser.ModelOffsetZ = 0;
GMAT Chaser.ModelRotationX = 0;
GMAT Chaser.ModelRotationY = 0;
GMAT Chaser.ModelRotationZ = 0;
GMAT Chaser.ModelScale = 1;
GMAT Chaser.AttitudeDisplayStateType = 'Quaternion';
GMAT Chaser.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT Chaser.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT Chaser.EulerAngleSequence = '321';

Create Spacecraft Spacecraft_target;
GMAT Spacecraft_target.DateFormat = UTCGregorian;
GMAT Spacecraft_target.Epoch = '01 Jan 2000 11:59:28.000';
GMAT Spacecraft_target.CoordinateSystem = EarthMJ2000Eq;
GMAT Spacecraft_target.DisplayStateType = Keplerian;
GMAT Spacecraft_target.SMA = 9197.605605831628;
GMAT Spacecraft_target.ECC = 1.159524455636416e-15;
GMAT Spacecraft_target.INC = 28.50000000000003;
GMAT Spacecraft_target.RAAN = 360;
GMAT Spacecraft_target.AOP = 0;
GMAT Spacecraft_target.TA = 10.99999999999999;
GMAT Spacecraft_target.DryMass = 850;
GMAT Spacecraft_target.Cd = 2.2;
GMAT Spacecraft_target.Cr = 1.8;
GMAT Spacecraft_target.DragArea = 15;
GMAT Spacecraft_target.SRPArea = 1;
GMAT Spacecraft_target.SPADDragScaleFactor = 1;
GMAT Spacecraft_target.SPADSRPScaleFactor = 1;
GMAT Spacecraft_target.AtmosDensityScaleFactor = 1;
GMAT Spacecraft_target.ExtendedMassPropertiesModel = 'None';
GMAT Spacecraft_target.NAIFId = -10001001;
GMAT Spacecraft_target.NAIFIdReferenceFrame = -9001001;
GMAT Spacecraft_target.OrbitColor = Green;
GMAT Spacecraft_target.TargetColor = LightGray;
GMAT Spacecraft_target.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT Spacecraft_target.CdSigma = 1e+70;
GMAT Spacecraft_target.CrSigma = 1e+70;
GMAT Spacecraft_target.Id = 'SatId';
GMAT Spacecraft_target.Attitude = CoordinateSystemFixed;
GMAT Spacecraft_target.SPADSRPInterpolationMethod = Bilinear;
GMAT Spacecraft_target.SPADSRPScaleFactorSigma = 1e+70;
GMAT Spacecraft_target.SPADDragInterpolationMethod = Bilinear;
GMAT Spacecraft_target.SPADDragScaleFactorSigma = 1e+70;
GMAT Spacecraft_target.AtmosDensityScaleFactorSigma = 1e+70;
GMAT Spacecraft_target.ModelFile = 'aura.3ds';
GMAT Spacecraft_target.ModelOffsetX = 0;
GMAT Spacecraft_target.ModelOffsetY = 0;
GMAT Spacecraft_target.ModelOffsetZ = 0;
GMAT Spacecraft_target.ModelRotationX = 0;
GMAT Spacecraft_target.ModelRotationY = 0;
GMAT Spacecraft_target.ModelRotationZ = 0;
GMAT Spacecraft_target.ModelScale = 1;
GMAT Spacecraft_target.AttitudeDisplayStateType = 'Quaternion';
GMAT Spacecraft_target.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT Spacecraft_target.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT Spacecraft_target.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn ImpulsiveBurn1;
GMAT ImpulsiveBurn1.CoordinateSystem = Local;
GMAT ImpulsiveBurn1.Origin = Earth;
GMAT ImpulsiveBurn1.Axes = VNB;
GMAT ImpulsiveBurn1.Element1 = 0;
GMAT ImpulsiveBurn1.Element2 = 0;
GMAT ImpulsiveBurn1.Element3 = 0;
GMAT ImpulsiveBurn1.DecrementMass = false;
GMAT ImpulsiveBurn1.Isp = 300;
GMAT ImpulsiveBurn1.GravitationalAccel = 9.81;

Create ImpulsiveBurn ImpulsiveBurn2;
GMAT ImpulsiveBurn2.CoordinateSystem = Local;
GMAT ImpulsiveBurn2.Origin = Earth;
GMAT ImpulsiveBurn2.Axes = VNB;
GMAT ImpulsiveBurn2.Element1 = 0;
GMAT ImpulsiveBurn2.Element2 = 0;
GMAT ImpulsiveBurn2.Element3 = 0;
GMAT ImpulsiveBurn2.DecrementMass = false;
GMAT ImpulsiveBurn2.Isp = 300;
GMAT ImpulsiveBurn2.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DC1;
GMAT DC1.ShowProgress = true;
GMAT DC1.ReportStyle = Normal;
GMAT DC1.ReportFile = 'DifferentialCorrectorDC1.data';
GMAT DC1.MaximumIterations = 25;
GMAT DC1.DerivativeMethod = ForwardDifference;
GMAT DC1.Algorithm = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.002173913043478261 0 ];
GMAT DefaultOrbitView.Size = [ 0.5 0.45 ];
GMAT DefaultOrbitView.RelativeZOrder = 971;
GMAT DefaultOrbitView.Maximized = true;
GMAT DefaultOrbitView.Add = {Chaser, Spacecraft_target, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ 0 0 30000 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.002173913043478261 0.453030303030303 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.5 0.45 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 702;
GMAT DefaultGroundTrackPlot.Maximized = false;
GMAT DefaultGroundTrackPlot.Add = {Chaser};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate 'Propagate1' DefaultProp(Chaser) DefaultProp(Spacecraft_target) {Chaser.ElapsedSecs = 12000.0, Spacecraft_target.ElapsedSecs = 12000.0, OrbitColor = [255 255 255]};
Target DC1 {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary DC1(ImpulsiveBurn1.Element1 = 1.5, {Perturbation = 0.0001, Lower = 0.0, Upper = 3.14159, MaxStep = 0.2, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver ImpulsiveBurn1(Chaser);
   
   BeginScript
      GMAT Chaser.OrbitColor = Yellow;
      GMAT Spacecraft_target.OrbitColor = White;
   EndScript;
   Propagate 'Propagate2' DefaultProp(Chaser) DefaultProp(Spacecraft_target) {Chaser.Earth.Apoapsis};
   Achieve DC1(Chaser.Earth.RMAG = Spacecraft_target.Earth.SMA, {Tolerance = 0.1});
EndTarget;  % For targeter DC1
Target DC1 {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary 'Vary2' DC1(ImpulsiveBurn2.Element1 = 0.5, {Perturbation = 0.0001, Lower = 0.0, Upper = 3.14159, MaxStep = 0.2, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver 'Maneuver2' ImpulsiveBurn2(Chaser);
   Achieve 'Achieve2' DC1(Chaser.Earth.ECC = 0, {Tolerance = 0.1});
   
   BeginScript
      GMAT Chaser.OrbitColor = Red;
      GMAT Spacecraft_target.OrbitColor = Red;
   EndScript;
   Propagate 'Propagate3' DefaultProp(Chaser) DefaultProp(Spacecraft_target) {Chaser.ElapsedSecs = 12000.0, Spacecraft_target.ElapsedSecs = 12000};
EndTarget;  % For targeter DC1
