%General Mission Analysis Tool(GMAT) Script



%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
GMAT DefaultSC.DateFormat = TAIModJulian;
GMAT DefaultSC.Epoch = '21545';
GMAT DefaultSC.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC.DisplayStateType = Keplerian;
GMAT DefaultSC.SMA = 26334.99999999997;
GMAT DefaultSC.ECC = 0.7299999999999996;
GMAT DefaultSC.INC = 63.43;
GMAT DefaultSC.RAAN = 360;
GMAT DefaultSC.AOP = 270;
GMAT DefaultSC.TA = 360;
GMAT DefaultSC.DryMass = 850;
GMAT DefaultSC.Cd = 2.2;
GMAT DefaultSC.Cr = 1.8;
GMAT DefaultSC.DragArea = 15;
GMAT DefaultSC.SRPArea = 1;
GMAT DefaultSC.SPADDragScaleFactor = 1;
GMAT DefaultSC.SPADSRPScaleFactor = 1;
GMAT DefaultSC.AtmosDensityScaleFactor = 1;
GMAT DefaultSC.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC.NAIFId = -10001001;
GMAT DefaultSC.NAIFIdReferenceFrame = -9001001;
GMAT DefaultSC.OrbitColor = Red;
GMAT DefaultSC.TargetColor = Teal;
GMAT DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC.CdSigma = 1e+70;
GMAT DefaultSC.CrSigma = 1e+70;
GMAT DefaultSC.Id = 'SatId';
GMAT DefaultSC.Attitude = CoordinateSystemFixed;
GMAT DefaultSC.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC.ModelFile = 'aura.3ds';
GMAT DefaultSC.ModelOffsetX = 0;
GMAT DefaultSC.ModelOffsetY = 0;
GMAT DefaultSC.ModelOffsetZ = 0;
GMAT DefaultSC.ModelRotationX = 0;
GMAT DefaultSC.ModelRotationY = 0;
GMAT DefaultSC.ModelRotationZ = 0;
GMAT DefaultSC.ModelScale = 1;
GMAT DefaultSC.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC.AttitudeCoordinateSystem = EarthFixed;
GMAT DefaultSC.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC2;
GMAT DefaultSC2.DateFormat = TAIModJulian;
GMAT DefaultSC2.Epoch = '21545';
GMAT DefaultSC2.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC2.DisplayStateType = Keplerian;
GMAT DefaultSC2.SMA = 26334.99999999977;
GMAT DefaultSC2.ECC = 0.7299999999999977;
GMAT DefaultSC2.INC = 63.43;
GMAT DefaultSC2.RAAN = 120;
GMAT DefaultSC2.AOP = 270.0000000000001;
GMAT DefaultSC2.TA = 359.9999987925818;
GMAT DefaultSC2.DryMass = 850;
GMAT DefaultSC2.Cd = 2.2;
GMAT DefaultSC2.Cr = 1.8;
GMAT DefaultSC2.DragArea = 15;
GMAT DefaultSC2.SRPArea = 1;
GMAT DefaultSC2.SPADDragScaleFactor = 1;
GMAT DefaultSC2.SPADSRPScaleFactor = 1;
GMAT DefaultSC2.AtmosDensityScaleFactor = 1;
GMAT DefaultSC2.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC2.NAIFId = -10001001;
GMAT DefaultSC2.NAIFIdReferenceFrame = -9001001;
GMAT DefaultSC2.OrbitColor = [255 255 0];
GMAT DefaultSC2.TargetColor = Teal;
GMAT DefaultSC2.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC2.CdSigma = 1e+70;
GMAT DefaultSC2.CrSigma = 1e+70;
GMAT DefaultSC2.Id = 'SatId';
GMAT DefaultSC2.Attitude = CoordinateSystemFixed;
GMAT DefaultSC2.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC2.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC2.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC2.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC2.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC2.ModelFile = 'aura.3ds';
GMAT DefaultSC2.ModelOffsetX = 0;
GMAT DefaultSC2.ModelOffsetY = 0;
GMAT DefaultSC2.ModelOffsetZ = 0;
GMAT DefaultSC2.ModelRotationX = 0;
GMAT DefaultSC2.ModelRotationY = 0;
GMAT DefaultSC2.ModelRotationZ = 0;
GMAT DefaultSC2.ModelScale = 1;
GMAT DefaultSC2.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC2.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC2.AttitudeCoordinateSystem = EarthFixed;
GMAT DefaultSC2.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC3;
GMAT DefaultSC3.DateFormat = TAIModJulian;
GMAT DefaultSC3.Epoch = '21545';
GMAT DefaultSC3.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC3.DisplayStateType = Keplerian;
GMAT DefaultSC3.SMA = 26335.00000000004;
GMAT DefaultSC3.ECC = 0.7300000000000005;
GMAT DefaultSC3.INC = 63.43;
GMAT DefaultSC3.RAAN = 240;
GMAT DefaultSC3.AOP = 270.0000000000002;
GMAT DefaultSC3.TA = 359.9999987925818;
GMAT DefaultSC3.DryMass = 850;
GMAT DefaultSC3.Cd = 2.2;
GMAT DefaultSC3.Cr = 1.8;
GMAT DefaultSC3.DragArea = 15;
GMAT DefaultSC3.SRPArea = 1;
GMAT DefaultSC3.SPADDragScaleFactor = 1;
GMAT DefaultSC3.SPADSRPScaleFactor = 1;
GMAT DefaultSC3.AtmosDensityScaleFactor = 1;
GMAT DefaultSC3.ExtendedMassPropertiesModel = 'None';
GMAT DefaultSC3.NAIFId = -10001001;
GMAT DefaultSC3.NAIFIdReferenceFrame = -9001001;
GMAT DefaultSC3.OrbitColor = [255 255 255];
GMAT DefaultSC3.TargetColor = Teal;
GMAT DefaultSC3.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC3.CdSigma = 1e+70;
GMAT DefaultSC3.CrSigma = 1e+70;
GMAT DefaultSC3.Id = 'SatId';
GMAT DefaultSC3.Attitude = CoordinateSystemFixed;
GMAT DefaultSC3.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC3.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC3.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC3.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC3.AtmosDensityScaleFactorSigma = 1e+70;
GMAT DefaultSC3.ModelFile = 'aura.3ds';
GMAT DefaultSC3.ModelOffsetX = 0;
GMAT DefaultSC3.ModelOffsetY = 0;
GMAT DefaultSC3.ModelOffsetZ = 0;
GMAT DefaultSC3.ModelRotationX = 0;
GMAT DefaultSC3.ModelRotationY = 0;
GMAT DefaultSC3.ModelRotationZ = 0;
GMAT DefaultSC3.ModelScale = 1;
GMAT DefaultSC3.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC3.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC3.AttitudeCoordinateSystem = EarthFixed;
GMAT DefaultSC3.EulerAngleSequence = '321';












%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 2;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 0;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.4528985507246377 0 ];
GMAT DefaultOrbitView.Size = [ 0.5 0.45 ];
GMAT DefaultOrbitView.RelativeZOrder = 21;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {DefaultSC, DefaultSC2, DefaultSC3, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ 90000 0 0 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = All;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.1115942028985507 0.1651515151515152 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.5 0.45 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 17;
GMAT DefaultGroundTrackPlot.Maximized = false;
GMAT DefaultGroundTrackPlot.Add = {DefaultSC, DefaultSC2, DefaultSC3};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create XYPlot XYPlot1;
GMAT XYPlot1.SolverIterations = Current;
GMAT XYPlot1.UpperLeft = [ 0.0007246376811594203 0 ];
GMAT XYPlot1.Size = [ 0.5 0.7893939393939394 ];
GMAT XYPlot1.RelativeZOrder = 5;
GMAT XYPlot1.Maximized = false;
GMAT XYPlot1.XVariable = DefaultSC.Earth.Longitude;
GMAT XYPlot1.YVariables = {DefaultSC.Earth.Latitude};
GMAT XYPlot1.ShowGrid = true;
GMAT XYPlot1.ShowPlot = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView2;
GMAT DefaultOrbitView2.SolverIterations = Current;
GMAT DefaultOrbitView2.UpperLeft = [ 0.3673913043478261 0.446969696969697 ];
GMAT DefaultOrbitView2.Size = [ 0.5 0.45 ];
GMAT DefaultOrbitView2.RelativeZOrder = 40;
GMAT DefaultOrbitView2.Maximized = false;
GMAT DefaultOrbitView2.Add = {DefaultSC, DefaultSC2, DefaultSC3, Earth};
GMAT DefaultOrbitView2.CoordinateSystem = EarthFixed;
GMAT DefaultOrbitView2.DrawObject = [ true true true true ];
GMAT DefaultOrbitView2.DataCollectFrequency = 1;
GMAT DefaultOrbitView2.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView2.NumPointsToRedraw = 0;
GMAT DefaultOrbitView2.ShowPlot = true;
GMAT DefaultOrbitView2.MaxPlotPoints = 20000;
GMAT DefaultOrbitView2.ShowLabels = true;
GMAT DefaultOrbitView2.ViewPointReference = Earth;
GMAT DefaultOrbitView2.ViewPointVector = [ 50000 0 0 ];
GMAT DefaultOrbitView2.ViewDirection = Earth;
GMAT DefaultOrbitView2.ViewScaleFactor = 1;
GMAT DefaultOrbitView2.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView2.ViewUpAxis = Z;
GMAT DefaultOrbitView2.EclipticPlane = Off;
GMAT DefaultOrbitView2.XYPlane = On;
GMAT DefaultOrbitView2.WireFrame = Off;
GMAT DefaultOrbitView2.Axes = On;
GMAT DefaultOrbitView2.Grid = Off;
GMAT DefaultOrbitView2.SunLine = Off;
GMAT DefaultOrbitView2.UseInitialView = On;
GMAT DefaultOrbitView2.StarCount = 7000;
GMAT DefaultOrbitView2.EnableStars = On;
GMAT DefaultOrbitView2.EnableConstellations = On;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC, DefaultSC2, DefaultSC3) {DefaultSC.ElapsedDays = 20};
