%General Mission Analysis Tool(GMAT) Script
%Created: 2025-12-18 20:50:04


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = UTCGregorian;
DefaultSC.Epoch = '13 Feb 2013 10:02:00.000';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Keplerian;
DefaultSC.SMA = 7079.999999999998;
DefaultSC.ECC = 9.999999999996538e-05;
DefaultSC.INC = 49.99999999999999;
DefaultSC.RAAN = 170;
DefaultSC.AOP = 1.207418269725733e-06;
DefaultSC.TA = 359.9999991462263;
DefaultSC.DryMass = 850;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.8;
DefaultSC.DragArea = 15;
DefaultSC.SRPArea = 1;
DefaultSC.SPADDragScaleFactor = 1;
DefaultSC.SPADSRPScaleFactor = 1;
DefaultSC.AtmosDensityScaleFactor = 1;
DefaultSC.ExtendedMassPropertiesModel = 'None';
DefaultSC.NAIFId = -10005001;
DefaultSC.NAIFIdReferenceFrame = -9005001;
DefaultSC.OrbitColor = Red;
DefaultSC.TargetColor = Teal;
DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
DefaultSC.CdSigma = 1e+70;
DefaultSC.CrSigma = 1e+70;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
DefaultSC.SPADDragInterpolationMethod = Bilinear;
DefaultSC.SPADDragScaleFactorSigma = 1e+70;
DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
DefaultSC.ModelFile = 'aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 1;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn ImpulsiveBurn1;
ImpulsiveBurn1.CoordinateSystem = Local;
ImpulsiveBurn1.Origin = Earth;
ImpulsiveBurn1.Axes = VNB;
ImpulsiveBurn1.Element1 = 0;
ImpulsiveBurn1.Element2 = 0;
ImpulsiveBurn1.Element3 = 0;
ImpulsiveBurn1.DecrementMass = false;
ImpulsiveBurn1.Isp = 300;
ImpulsiveBurn1.GravitationalAccel = 9.81;

Create ImpulsiveBurn ImpulsiveBurn2;
ImpulsiveBurn2.CoordinateSystem = Local;
ImpulsiveBurn2.Origin = Earth;
ImpulsiveBurn2.Axes = VNB;
ImpulsiveBurn2.Element1 = 0;
ImpulsiveBurn2.Element2 = 0;
ImpulsiveBurn2.Element3 = 0;
ImpulsiveBurn2.DecrementMass = false;
ImpulsiveBurn2.Isp = 300;
ImpulsiveBurn2.GravitationalAccel = 9.81;

Create ImpulsiveBurn ImpulsiveBurn3;
ImpulsiveBurn3.CoordinateSystem = Local;
ImpulsiveBurn3.Origin = Earth;
ImpulsiveBurn3.Axes = VNB;
ImpulsiveBurn3.Element1 = 0;
ImpulsiveBurn3.Element2 = 0;
ImpulsiveBurn3.Element3 = 0;
ImpulsiveBurn3.DecrementMass = false;
ImpulsiveBurn3.Isp = 300;
ImpulsiveBurn3.GravitationalAccel = 9.81;

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DefaultDC;
DefaultDC.ShowProgress = true;
DefaultDC.ReportStyle = Normal;
DefaultDC.ReportFile = 'DifferentialCorrectorDefaultDC.data';
DefaultDC.MaximumIterations = 25;
DefaultDC.DerivativeMethod = ForwardDifference;
DefaultDC.Algorithm = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.002293577981651376 0 ];
DefaultOrbitView.Size = [ 0.5 0.4255910987482615 ];
DefaultOrbitView.RelativeZOrder = 2204;
DefaultOrbitView.Maximized = true;
DefaultOrbitView.Add = {DefaultSC, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.MaxPlotPoints = 20000;
DefaultOrbitView.ShowLabels = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.002293577981651376 0.4033379694019472 ];
DefaultGroundTrackPlot.Size = [ 0.5 0.4005563282336578 ];
DefaultGroundTrackPlot.RelativeZOrder = 2186;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {DefaultSC};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create ReportFile ReportFile1;
ReportFile1.SolverIterations = Current;
ReportFile1.UpperLeft = [ 0 0 ];
ReportFile1.Size = [ 0 0 ];
ReportFile1.RelativeZOrder = 0;
ReportFile1.Maximized = false;
ReportFile1.Filename = 'Report_R3I.txt';
ReportFile1.Precision = 16;
ReportFile1.Add = {DefaultSC.A1ModJulian, DefaultSC.EarthMJ2000Eq.X, DefaultSC.EarthMJ2000Eq.BrouwerShortSMA, DefaultSC.EarthMJ2000Eq.BrouwerShortINC, DefaultSC.EarthMJ2000Eq.BrouwerShortRAAN, DefaultSC.EarthMJ2000Eq.BrouwerShortECC};
ReportFile1.WriteHeaders = true;
ReportFile1.LeftJustify = On;
ReportFile1.ZeroFill = Off;
ReportFile1.FixedWidth = true;
ReportFile1.Delimiter = ' ';
ReportFile1.ColumnWidth = 23;
ReportFile1.WriteReport = true;


Create XYPlot XYPlotSMA;
XYPlotSMA.SolverIterations = Current;
XYPlotSMA.UpperLeft = [ 0 0 ];
XYPlotSMA.Size = [ 0 0 ];
XYPlotSMA.RelativeZOrder = 0;
XYPlotSMA.Maximized = false;
XYPlotSMA.XVariable = DefaultSC.A1ModJulian;
XYPlotSMA.YVariables = {DefaultSC.EarthMJ2000Eq.BrouwerLongSMA};
XYPlotSMA.ShowGrid = true;
XYPlotSMA.ShowPlot = true;

Create XYPlot XYPlotECC;
XYPlotECC.SolverIterations = Current;
XYPlotECC.UpperLeft = [ 0.00382262996941896 0.4061196105702364 ];
XYPlotECC.Size = [ 0.5 0.4005563282336578 ];
XYPlotECC.RelativeZOrder = 2072;
XYPlotECC.Maximized = false;
XYPlotECC.XVariable = DefaultSC.A1ModJulian;
XYPlotECC.YVariables = {DefaultSC.EarthMJ2000Eq.BrouwerShortECC};
XYPlotECC.ShowGrid = true;
XYPlotECC.ShowPlot = true;

Create XYPlot XYPlotINC;
XYPlotINC.SolverIterations = Current;
XYPlotINC.UpperLeft = [ 0.04587155963302753 0.4617524339360223 ];
XYPlotINC.Size = [ 0.5 0.4005563282336578 ];
XYPlotINC.RelativeZOrder = 2077;
XYPlotINC.Maximized = false;
XYPlotINC.XVariable = DefaultSC.A1ModJulian;
XYPlotINC.YVariables = {DefaultSC.EarthMJ2000Eq.BrouwerShortINC};
XYPlotINC.ShowGrid = true;
XYPlotINC.ShowPlot = true;

Create XYPlot XYPlotRAAN;
XYPlotRAAN.SolverIterations = Current;
XYPlotRAAN.UpperLeft = [ 0 0 ];
XYPlotRAAN.Size = [ 0 0 ];
XYPlotRAAN.RelativeZOrder = 0;
XYPlotRAAN.Maximized = false;
XYPlotRAAN.XVariable = DefaultSC.A1ModJulian;
XYPlotRAAN.YVariables = {DefaultSC.EarthMJ2000Eq.BrouwerShortRAAN};
XYPlotRAAN.ShowGrid = true;
XYPlotRAAN.ShowPlot = true;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate 'PropagateTou1' DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 112.4225978879824};
Target 'ReachRb' DefaultDC {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary DefaultDC(ImpulsiveBurn1.Element1 = 1.346148687032999, {Perturbation = 0.0001, Lower = -2, Upper = 3, MaxStep = 0.1, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver ImpulsiveBurn1(DefaultSC);
   Propagate 'PropagateToApo' DefaultProp(DefaultSC) {DefaultSC.Earth.Apoapsis, OrbitColor = [0 128 255]};
   Achieve 'AchieveRb' DefaultDC(DefaultSC.Earth.RMAG = 16171.316475, {Tolerance = 0.1});
   Achieve 'AchieveTA' DefaultDC(DefaultSC.Earth.TA = 180, {Tolerance = 0.1});
EndTarget;  % For targeter DefaultDC
Target 'PurePlaneChange' DefaultDC {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary DefaultDC(ImpulsiveBurn2.Element1 = -1.303867760385782, {Perturbation = 0.0001, Lower = -3, Upper = 2, MaxStep = 0.1, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Vary DefaultDC(ImpulsiveBurn2.Element2 = -2.89884976848358, {Perturbation = 0.0001, Lower = -5, Upper = 3, MaxStep = 0.1, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver ImpulsiveBurn2(DefaultSC);
   Propagate 'PropagateToPer' DefaultProp(DefaultSC) {DefaultSC.Earth.Periapsis, OrbitColor = [255 128 255]};
   Achieve 'AchieveSMA' DefaultDC(DefaultSC.Earth.RMAG = 7080, {Tolerance = 0.1});
   Achieve 'AchieveINC' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortINC = 98.2, {Tolerance = 0.1});
   Achieve 'AchieveRAAN' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortRAAN = 175.155111, {Tolerance = 0.1});
EndTarget;  % For targeter DefaultDC
Target 'FinalOrbit' DefaultDC {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary DefaultDC(ImpulsiveBurn3.Element1 = -1.346148687032999, {Perturbation = 0.0001, Lower = -3, Upper = 3, MaxStep = 0.1, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver ImpulsiveBurn3(DefaultSC);
   Achieve 'AchieveSMA' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortSMA = 7080, {Tolerance = 0.1});
   Achieve 'AchieveINC' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortINC = 98.2, {Tolerance = 0.1});
   Achieve 'AchieveRAAN' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortRAAN = 175.155111, {Tolerance = 0.1});
   Achieve 'AchieveECC' DefaultDC(DefaultSC.EarthMJ2000Eq.BrouwerShortECC = 0.0001, {Tolerance = 0.1});
EndTarget;  % For targeter DefaultDC
Propagate 'PropagateFinalOrbit' DefaultProp(DefaultSC) {DefaultSC.ElapsedDays = 0.068619432901336, OrbitColor = [255 128 0]};
